### PR TITLE
[MRG] Add travis setup for linux and osx

### PR DESCRIPTION
**Pull request by betatim**
Get going with travis for linux.

### CODE REVIEW

**Comment by betatim** [comment]
That seems to work.

**Comment by rgbkrk** [comment]
Ready for merge? (take off the WIP tag if so)

**Comment by betatim** [comment]
Decided to add osx to this as well ...

**Review by rgbkrk — APPROVED** [review]

**Comment by rgbkrk** [comment]
Oh hey look, it built!

**Pull request merged**
